---
modules-search: [ local ]

instances:
  - module: shellprocess
    id: keskos_prepare_target
    config: prepare-target.conf
    weight: 1
  - module: shellprocess
    id: keskos_postinstall
    config: postinstall.conf
    weight: 1

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess@keskos_prepare_target
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - initcpio
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - shellprocess@keskos_postinstall
      - umount
  - show:
      - finished

branding: keskos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
