---
modules-search: [ local ]

instances:
  - module: shellprocess
    id: keskos_prepare_target
    config: prepare-target.conf
    weight: 1
  - module: packagechooser
    id: keskos_browser
    config: keskos-browser.conf
    weight: 1
  - module: packagechooser
    id: keskos_browser_theme
    config: keskos-browser-theme.conf
    weight: 1
  - module: packagechooser
    id: keskos_bundles
    config: keskos-bundles.conf
    weight: 1
  - module: packagechooser
    id: keskos_desktop_profile
    config: keskos-desktop-profile.conf
    weight: 1
  - module: packagechooser
    id: keskos_addons
    config: keskos-addons.conf
    weight: 1
  - module: notesqml
    id: keskos_review
    config: keskos-review.conf
    weight: 1
  - module: shellprocess
    id: keskos_postinstall
    config: postinstall.conf
    weight: 1

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - packagechooser@keskos_browser
      - packagechooser@keskos_browser_theme
      - packagechooser@keskos_bundles
      - packagechooser@keskos_desktop_profile
      - packagechooser@keskos_addons
      - notesqml@keskos_review
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess@keskos_prepare_target
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - initcpio
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - keskoschoices
      - packages
      - services-systemd
      - bootloader
      - shellprocess@keskos_postinstall
      - umount
  - show:
      - finished

branding: keskos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
