---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: "EFI"

userSwapChoices:
  - none
  - small
  - suspend
  - file

luksGeneration: luks1
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "ext4"
