---
dontChroot: true
timeout: 300
verbose: true
script:
  - command: "TARGET_ROOT='${ROOT}' /usr/local/bin/keskos-prepare-target-root"
    timeout: 300
    verbose: true

i18n:
  name: "Preparing installed system layout"
