---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - audio
  - video
  - network
  - storage
  - name: wheel
    must_exist: false
    system: true

sudoersGroup: wheel
autologinGroup: autologin
sudoersConfigureWithGroup: false
setRootPassword: false
doReusePassword: false
displayAutologin: false
doAutologin: false

passwordRequirements:
  minLength: 8
  maxLength: 64
  libpwquality:
    - minlen=8
    - maxrepeat=3
    - maxsequence=3

allowWeakPasswords: false
allowWeakPasswordsDefault: false

user:
  shell: /bin/bash
  forbidden_names: [ root ]
  home_permissions: "o700"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "kesk-${login}"
  forbidden_names: [ localhost ]

allowActiveDirectory: false
